import Head from 'next/head'
import { Layout } from '@/components/layouts/Layout'
import { GetStaticProps, NextPage } from 'next'
import { pokeApi } from '../api'
import { PokemonListResponse, SmallPokemon } from '../interfaces'
import { Card, Grid, Row, Text } from '@nextui-org/react'
import { PokemonCard } from '@/components/pokemon'
import Image from 'next/image'

interface Props{
  pokemons: SmallPokemon[]
}

const Home: NextPage<Props> = ({ pokemons }) => {
  return (
    <>
      <Head>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      
      <Layout title='Pokemon App'>
        <>
          <Image src='/img/pokemon-banner.jpg' alt='pokemon banner'
          width={450}
          height={150} style={{margin:'0 auto', display: 'block'}}/>
          <Grid.Container gap={ 2 } justify='flex-start'>
            {
              pokemons.map((pokemon)=>(
                <PokemonCard key={pokemon.id} pokemon={pokemon} />
              ))}
          </Grid.Container>
        </>    
      </Layout>
    </>
  )
}

export const getStaticProps:GetStaticProps = async (ctx) => {
  const { data } = await pokeApi.get<PokemonListResponse>('/pokemon?limit=151')

  const pokemons: SmallPokemon[] = data.results.map( (poke, i) => ({
    ...poke,
    id: i + 1,
    img: `https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/dream-world/${i+1}.svg`
  }) )

  return {
    props: {
      pokemons
    }
  }
}

export default Home